### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by lucc** [scheibler/khard#204]
Currently we have a lot of documentation in the README. This issue is for planning and discussing further changes to improve the documentation.

The plan is to make the README smaller and move the documentation to the doc folder where we use sphinx. This was started in #201.

For the minimal README we want at least this information:
* short description of khard
* (pip) installation instructions
* a few usage examples.
* pointers to the documentation

I think the plan looks like this:
* [x] extend the sphinx documentation 
  * [x] configuration (#216)
  * [x] command line usage (#216)
  * [x] scripting (#229)
  * [x] integration with email clients and other programs (#216)
* [x] reduce the README (#216)
* [x] write man pages
  * [x] main man page for khard (#201)
  * [x] for the config file
* [x] publish the docs somewhere, ~e.g.~ [readthedocs](https://khard.readthedocs.io/en/latest/)

**Comment by lucc** [comment]
We should also check if and how we can use the --help output to auto-generate a listing of all subcommands and their options. This should then be used in the man page and the command line usage section.

**Comment by lucc** [comment]
https://sphinx-argparse.readthedocs.io/en/stable/index.html

**Comment by lucc** [comment]
Maybe we could use typehints to document the parameter and return types: https://github.com/agronholm/sphinx-autodoc-typehints
